spring:
  ai:
    model:
      chat: openai
      embedding: openai
    openai:
      base-url: ${OPENAI_BASE_URL:}
      api-key: ${OPENAI_API_KEY:}
      chat:
        options:
          model: ${OPENAI_CHAT_MODEL:}
      embedding:
        options:
          model: ${OPENAI_EMBEDDING_MODEL:}
          encoding-format: float
    vectorstore:
      pgvector:
        dimensions: ${EMBEDDING_DIMENSIONS:3072}
